{{- if .Values.wtpapi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wtp.serviceAccountName" . }}
  labels:
    {{- include "wtp.labels" . | nindent 4 }}
  {{- with .Values.wtpapi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.wtpapi.serviceAccount.automount }}
{{- end }}
