apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wtp.name" . }}-pyapi-pv-claim
  labels:
    helm.sh/chart: {{ include "wtp.chart" . }}
    app.kubernetes.io/name: {{ include "wtp.name" . }}-pyapi-pv-claim
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ include "wtp.name" . }}-pyapi-pv
  storageClassName: manual