apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wtp.name" . }}-dsapidb-dpl
  labels:
    helm.sh/chart: {{ include "wtp.chart" . }}
    app.kubernetes.io/name: {{ include "wtp.name" . }}-dsapidb-dpl
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  # annotations:
  #   "helm.sh/hook": pre-install
  #   "helm.sh/hook-weight": "-2"
  #   "helm.sh/hook-delete-policy": before-hook-creation    
spec:
  replicas: {{ default 1 .Values.dsapidb.replicaCount | int }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wtp.name" . }}-dsapidb-dpl
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "wtp.chart" . }}
        app.kubernetes.io/name: {{ include "wtp.name" . }}-dsapidb-dpl
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      # securityContext:
      #   fsGroup: 1000  # GID dari knwa
      #   fsGroupChangePolicy: Always
      #   fsGroup: 1001    
      # initContainers:
      # - name: fix-permissions
      #   image: busybox
      #   securityContext:
      #     runAsUser: 1000
      #     runAsGroup: 1000
      #     # allowPrivilegeEscalation: true
      #   command:
      #     - /bin/sh
      #     - -c
      #     - |
      #       mkdir -p /var/lib/postgresql/data /var/lib/postgresql/data/pgdata
      #       chmod 777 /var/lib/postgresql /var/lib/postgresql/data/pgdata
      #       xargs chown -R 1000:1000 /var/lib/postgresql/data /var/lib/postgresql/data/pgdata
      #   volumeMounts:
      #   - name: ds-postgres-persistance-storage
      #     mountPath: /var/lib/postgresql/data
      containers:
      - name: {{ .Chart.Name }}-dsapidb
        image: "{{ .Values.dsapidb.postgresql.image.repository }}:{{ .Values.dsapidb.postgresql.image.tag | default "latest" }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.dsapidb.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.dsapidb.postgresql.password }}"
        - name: POSTGRES_DB
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            # subPath: data
            name: ds-postgres-persistance-storage
          - name: postgre-initdb
            mountPath: /docker-entrypoint-initdb.d
        # securityContext:
        #   runAsUser: 1000  # UID dari knwa
        #   runAsGroup: 1000 # GID dari knwa
          # fsGroup: 1000    # GID dari knwa            
      volumes:
        - name: ds-postgres-persistance-storage
          persistentVolumeClaim:
            claimName: {{ include "wtp.name" . }}-ds-postgres-pv-claim
        - name: postgre-initdb
          configMap:
            name: db-script-config
        # - name: script-volume
        #   emptyDir: {}