apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wtp.name" . }}-ds-postgres-pv-volume
  labels:
    type: local
    helm.sh/chart: {{ include "wtp.chart" . }}
    app.kubernetes.io/name: {{ include "wtp.name" . }}-ds-postgres-pv-volume
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/water-status-data/postgresql/dsapidb"